name: Build & Deploy Static Blog

on:
  push:
    branches:
      - main
  workflow_dispatch: {} # allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies and build
        run: |
          pip install markdown
          python3 site_generator/build.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init

      - name: Terraform Apply
        run: |
          cd infrastructure
          terraform apply -auto-approve -var="bucket_name=${{ secrets.S3_BUCKET_NAME }}"

      - name: Sync site to S3
        run: |
          aws s3 sync output/ s3://${{ secrets.S3_BUCKET_NAME }}/ --delete

